#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat|fix|doc|css|pkg|refactor|ci|etc):.*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "=========================================================================="
  echo "======================   🚨 WRONG COMMIT MESSAGE!   ======================"
  echo "=========================================================================="
  echo "== Format should be => [header]: [What was done for Why]                =="
  echo "== Allowed Headers: feat, fix, doc, css, pkg, refactor, ci, etc         =="
  echo "== EXAMPLE => feat: Google login                                        =="
  echo "=========================================================================="
  echo "== Your commit message was =>" $message 
  echo "== For more information, check script in .husky/commit-msg or README.md =="
  echo "=========================================================================="
  exit 1
else
  echo "=========================================================================="
  echo "=======================      COMMIT CREATED!!      ======================="
  echo "=========================================================================="
fi